name = "TerminalUserInterfaces"
uuid = "408767e4-586b-40c7-9657-f9758988469a"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
version = "0.6.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Crossterm = "89a1a94d-67fa-4c27-8677-ab6d33b1ad6c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
KiwiConstraintSolver = "063317df-b1e6-4e84-b689-d7ba7b3726e4"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LoggingFormats = "98105f81-4425-4516-93fd-1664fb551ab6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Crayons = "4"
Crossterm = "0.5"
LoggingExtras = "1"
LoggingFormats = "1"
TextWrap = "1"
julia = "1"

[extras]
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"

[targets]
test = ["ReTest"]
