[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PalmerPenguins = "8b842266-38fa-440a-9b57-31493939ab85"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TerminalUserInterfaces = "408767e4-586b-40c7-9657-f9758988469a"
